In [2]:
# step 1: read packages
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# step -2 read datasets

In [4]:
import pandas as pd
pd.read_csv(r"D:\data files\Visadataset.csv")

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [5]:
pd.read_csv(r"D:\data files\bank.csv",sep=';')    #; will seperate sentences

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [3]:
#step-3 data quick checks

In [ ]:
# us visa_df
-visa_df.shape
-visa_df.size
-head
-tail
-dtypes
-columns
-isnull
-info

In [6]:
visa_df=pd.read_csv(r"D:\data files\Visadataset.csv")

In [7]:
visa_df.shape
print(f'the number of rows are:{visa_df.shape[0]}')
print(f'the number of columns are:{visa_df.shape[1]}')

the number of rows are:25480
the number of columns are:12

In [8]:
type(visa_df)

pandas.core.frame.DataFrame

In [7]:
visa_df.size
# number of entries

305760

In [9]:
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [10]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [11]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [20]:
visa_df.columns
# what are columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [28]:
cols=visa_df.columns
cols=cols.tolist()

In [29]:
cols.index('yr_of_estab')

6

In [13]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

In [21]:
#how you are seeing a df in the numpy language
# pandas ===  numpy
#i df 25480 rows 12 columns
# numpy : bro i have a list hiving 12 values
#         these list are repeating 25480

np.array([[1,2,3,4]]).shape # i have a list of 4 values 1 time
# 1x4 shape
np.array([[1,2,3,4],[10,20,30,40]]) # i have a list of 4 values 2 times

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [22]:
np.array([[1,2,3,4],[10,20,30,40]]).shape # i have a list of 4 values 2 times

(2, 4)

In [19]:
#[[1,2,3,4......12],[],[]........25480]
visa_df      # pandas
visa_df.values   # numpy array

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [20]:
#[[1,2,3,4......12],[],[]........25480]
visa_df.values.shape

(25480, 12)

In [32]:
#loc-iloc

In [33]:
#visa_df.iloc[rows,columns]
#visa_df.iloc[start:stop:step,start:stop:step]
visa_df.iloc[2:6,3:7]
# rows: 2:6    2,3,4,5
# columns 3:7   3,4,5,6

  has_job_experience requires_job_training  no_of_employees  yr_of_estab
2                  N                     Y            44444         2008
3                  N                     N               98         1897
4                  Y                     N             1082         2005
5                  Y                     N             2339         2012

In [34]:
# loc will use ful we can provide direct columns names
# no need of indexes
cols=['has_job_experience','requires_job_training']
visa_df.loc[2:6,cols]

  has_job_experience requires_job_training
2                  N                     Y
3                  N                     N
4                  Y                     N
5                  Y                     N
6                  N                     N

In [35]:
visa_df.iloc[[100,200,300]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [36]:
visa_df.iloc[[100,200,300],:3]

     case_id continent education_of_employee
100  EZYV101      Asia              Master's
200  EZYV201      Asia             Doctorate
300  EZYV301      Asia              Master's

In [38]:
visa_df.iloc[[100,200,300],[3,4,9]]

    has_job_experience requires_job_training unit_of_wage
100                  Y                     N         Year
200                  Y                     N         Year
300                  Y                     N         Year

In [39]:
# every student should understand
# 1d and 2d
# list  []  numpy : 1D  pandas == series
# list  [[]] numpy: 2D  pandas == dataframe

In [26]:
visa_df       # dataframe has column names 
visa_df['continent']   # series has no column names

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [27]:
visa_df.values     # 2d in numpy and dataframe in pandas

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [41]:
visa_df['continent'].values   # 1d in numpy and dataframe in pandas

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [ ]:
visa_df
visa_df['continent']   #1d     series
visa_df[['continent']]   # 2d  dataframe
rows=[100,200,300]
visa_df.iloc[rows,3]   # 1d   series
visa_df.iloc[rows,[3]]   # 2d  df
visa_df.loc[rows,'continent']   # 1d      s
visa_df.loc[rows,['continent']]  # 2d     df

In [43]:
visa_df[['continent']].values

array([['Asia'],
       ['Asia'],
       ['Asia'],
       ...,
       ['Asia'],
       ['Asia'],
       ['Asia']], shape=(25480, 1), dtype=object)

In [28]:
visa_df              # df 2d
visa_df.values       #array 2d
# there are 12 columns
# a list has 12 values
# list is repeating 25480 rows

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [32]:
visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [33]:
visa_df['continent'].values # raw data

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [37]:
visa_df[['continent','case_status']]

      continent case_status
0          Asia      Denied
1          Asia   Certified
2          Asia      Denied
3          Asia      Denied
4        Africa   Certified
...         ...         ...
25475      Asia   Certified
25476      Asia   Certified
25477      Asia   Certified
25478      Asia   Certified
25479      Asia   Certified

[25480 rows x 2 columns]

In [38]:
visa_df[['continent','case_status']].values

array([['Asia', 'Denied'],
       ['Asia', 'Certified'],
       ['Asia', 'Denied'],
       ...,
       ['Asia', 'Certified'],
       ['Asia', 'Certified'],
       ['Asia', 'Certified']], shape=(25480, 2), dtype=object)

In [39]:
#1d is only one list ; raw data of a specific column
visa_df['continent'].values #[25480]

# 2d is a list has 2 values : df 2 column

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [ ]:
#every student should know
# how to convert a series to dataframe
 series a dictionary
                   keys tolist
                   values
# how to create a dataframe when you have a list
                     zip

In [ ]:
# dtypes
- every series is a key value pair
- every series is adictionary
- in dictionary if we want keys : keys()
- in dictionary if we want values : .values

In [7]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [8]:
visa_df.case_id

0           EZYV01
1           EZYV02
2           EZYV03
3           EZYV04
4           EZYV05
           ...
25475    EZYV25476
25476    EZYV25477
25477    EZYV25478
25478    EZYV25479
25479    EZYV25480
Name: case_id, Length: 25480, dtype: object

In [40]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [14]:
keys=visa_df.dtypes.keys().tolist()

In [41]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [15]:
values=visa_df.dtypes.values.tolist()

In [42]:
keys=visa_df.dtypes.keys().tolist()
values=visa_df.dtypes.values.tolist()
pd.DataFrame(zip(keys,values),columns=['Names','Data type'])

                    Names Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [17]:
pd.DataFrame(visa_df.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [43]:
pd.DataFrame(visa_df.dtypes).reset_index()

                    index        0
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

In [22]:
df=pd.DataFrame(visa_df.dtypes).reset_index()  # naming columns
df.columns=['Names','Data Type']
df

                    Names Data Type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [23]:
#task-2

In [47]:
visa_df.dtypes
# idea
# extract keys and values
# apply the for loop on values
# for i,j zip(values,key)
# if i == object
#    j

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [18]:
keys=visa_df.dtypes.keys().tolist()
values=visa_df.dtypes.values.tolist()

[dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O')]

In [46]:
keys=visa_df.dtypes.keys().tolist()
values=visa_df.dtypes.values.tolist()
cat,num=[],[]
for i,j in zip(keys,values):        # i is names j is dtypes
    if j=='object':
        cat.append(i)
    else:
        num.append(j)
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [48]:
visa_df.select_dtypes(include='object')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [49]:
visa_df.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [50]:
visa_df.select_dtypes(exclude='object')

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

In [35]:
visa_df.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')